export default {
  CHANGE: "CHANGE",
  TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",
  PUBLIC_URL:"PUBLICURLS",
  EDUCATION_ROLE_SUPERADMIN:"SUPERADMIN",
  EDUCATION_ROLE_ADMIN:"ORGADMIN",
  EDUCATION_ROLE_PARENT:"PARENT",
  EDUCATION_ROLE_STUDENT:"STUDENT",
  EDUCATION_ROLE_TEACHER:"TEACHER"


};
