export default {
  CHANGE: "CHANGE",
  TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",
  PUBLIC_URL:"PUBLICURLS",
  EDUCATION_ROLE_SUPERADMIN:"SUPERADMIN",
  EDUCATION_ROLE_ADMIN:"ORGADMIN",
  EDUCATION_ROLE_PARENT:"PARENT",
  EDUCATION_ROLE_STUDENT:"STUDENT",
  EDUCATION_ROLE_TEACHER:"TEACHER",
  NEWS_VIEWER:"VIEWER",
  NEWES_CREATOR:"CREATOR",
  NEWS_CREATOR_VIEWER:"CREATOR_VIEWER"

};
